### ISSUE TITLE
파싱 오류 수정

### ISSUE THREAD

**Issue by YJSoft** [YJSoft/namuhub#2]
```
ERROR:namuhub:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/namuhub.yjsoft.me/namuhub/__init__.py", line 33, in namu
    contribs = namuwiki.contrib(user)
  File "/var/www/namuhub.yjsoft.me/namuhub/namu.py", line 97, in contrib
    when = row.select('td')[2].string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by YJSoft** [comment]
완료
